// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jArkVNRidx5gEfh6oZkX8wj6cWxg98g',
    appId: '1:866193151629:web:31603df35d71b8a12b34c4',
    messagingSenderId: '866193151629',
    projectId: 'mipay-6c296',
    authDomain: 'mipay-6c296.firebaseapp.com',
    storageBucket: 'mipay-6c296.appspot.com',
    measurementId: 'G-3Z149ZCGHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8JvpdMCoPQdvhqhmSj1prquwHm7csSbw',
    appId: '1:866193151629:android:d212f965a4c191122b34c4',
    messagingSenderId: '866193151629',
    projectId: 'mipay-6c296',
    storageBucket: 'mipay-6c296.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6TvlgvyLZqaHryM_JQdrHtirLpMwv26E',
    appId: '1:866193151629:ios:1679e9afbc4a547e2b34c4',
    messagingSenderId: '866193151629',
    projectId: 'mipay-6c296',
    storageBucket: 'mipay-6c296.appspot.com',
    iosBundleId: 'com.navario.miInsights',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6TvlgvyLZqaHryM_JQdrHtirLpMwv26E',
    appId: '1:866193151629:ios:1679e9afbc4a547e2b34c4',
    messagingSenderId: '866193151629',
    projectId: 'mipay-6c296',
    storageBucket: 'mipay-6c296.appspot.com',
    iosBundleId: 'com.navario.miInsights',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6jArkVNRidx5gEfh6oZkX8wj6cWxg98g',
    appId: '1:866193151629:web:caf80429cc36effb2b34c4',
    messagingSenderId: '866193151629',
    projectId: 'mipay-6c296',
    authDomain: 'mipay-6c296.firebaseapp.com',
    storageBucket: 'mipay-6c296.appspot.com',
    measurementId: 'G-M5KTYKEV44',
  );

}